version: 2

project_name: claude-autopilot

before:
  hooks:
    - go test ./...

builds:
  - id: claude-autopilot
    main: .
    binary: claude-autopilot
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: checksums.txt

changelog:
  use: git
  sort: asc
